pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    environment {
        SCANNER_HOME = tool 'SonarScanner'
        IMAGE_NAME = "finance-me:v1"
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Source Code Checked Out'
            }
        }

        stage('Build') {
            steps {
                dir('finance-me') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('finance-me') {
                    withSonarQubeEnv('SonarQube') {
                        sh '''
                        $SCANNER_HOME/bin/sonar-scanner \
                        -Dsonar.projectKey=finance-me \
                        -Dsonar.projectName=finance-me \
                        -Dsonar.sources=src \
                        -Dsonar.java.binaries=target/classes
                        '''
                    }
                }
            }
        }

        stage('Trivy File Scan') {
            steps {
                dir('finance-me') {
                    sh 'trivy fs .'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('finance-me') {
                    sh 'docker build -t finance-me:v1 .'
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh 'trivy image finance-me:v1'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                docker rm -f finance-me-container || true
                docker run -d --name finance-me-container -p 8085:8080 finance-me:v1
                '''
            }
        }
    }
}
